### DISCUSSION TITLE
v0.3.0

### DISCUSSION THREAD

**Discussion by belal-i** [saint-hilaire/smartestate#51] [Announcements]
SmartEstate: Django app for real estate brokers. If you are a real estate broker, or want to become one, you can use this to easily manage your listings, clients, broker deals, manage your website, etc.

I wrote this app about 3 years ago, and have recently refactored and packaged it. This is still a beta version, but it's ready for use - you can easily set it up, because it's available on Docker Hub.

### Try the demo

https://smartestate.app/

#### Pull from Docker Hub

```
docker pull sainthilaire/smartestate
```

#### Basic docker-compose.yml
```yaml
services:
  db:
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_DATABASE: smartestate
      MYSQL_USER: smartestate
      MYSQL_PASSWORD: insecure-please-change
      MYSQL_ROOT_PASSWORD: insecure-please-change
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    image: sainthilaire/smartestate:latest
    restart: always
    ports:
      - "80:8000"
    environment:
      DEBUG: 0
      SECRET_KEY: insecure-please-change
      ALLOWED_HOSTS: your-web-host.com
      CSRF_TRUSTED_ORIGINS: "https://*.your-web-host.com"
      DATABASE_ENGINE: django.db.backends.mysql
      DATABASE_HOST: db
      DATABASE_NAME: smartestate
      DATABASE_USER: smartestate
      DATABASE_PASSWORD: insecure-please-change
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
```

**View on Docker Hub**: https://hub.docker.com/r/sainthilaire/smartestate

**View on PyPI**: https://pypi.org/project/smartestate/0.3.0/

**Full Changelog**: https://github.com/saint-hilaire/smartestate/compare/v0.2.0...v0.3.0

<hr /><em>This discussion was created from the release <a href='https://github.com/saint-hilaire/smartestate/releases/tag/v0.3.0'>v0.3.0</a>.</em>
